spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/test
    username: postgres
    password: aspg001430005
    driverClassName: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true